"""
SentinelForge — shared/models/fraud_case.py

PURPOSE:
    Defines Pydantic schemas for fraud scores, analyst investigations, LLM-generated
    structured case narratives, and human analyst review feedback.

ARCHITECTURE POSITION:
    Layer 0 (Foundation) → Exchanged between Real-Time Scorer (Layer 3),
    Investigation Service (Layer 4), FastAPI Router (Layer 5), and Retraining Loop (Layer 8).

HUMAN-IN-THE-LOOP DESIGN:
    Analyst review decisions serve as verified ground truth labels that populate the
    `labeled_data` table, closing the self-improving ML flywheel for both LightGBM
    and QLoRA LLM fine-tuning.
"""

from datetime import datetime, timezone
from enum import Enum
from typing import Any, Optional
from uuid import UUID, uuid4

from pydantic import BaseModel, Field


class RiskLabel(str, Enum):
    """Fraud risk severity categorization."""

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class CaseStatus(str, Enum):
    """Investigation lifecycle status."""

    PENDING = "pending"
    INVESTIGATING = "investigating"
    RESOLVED = "resolved"


class AnalystDecision(str, Enum):
    """Analyst review outcome."""

    APPROVED = "approved"      # Transaction deemed legitimate
    REJECTED = "rejected"      # Transaction confirmed fraudulent
    ESCALATED = "escalated"    # Case escalated to senior risk operations


class FraudScore(BaseModel):
    """
    Synchronous scoring prediction returned within <150ms auth path.
    """

    id: UUID = Field(default_factory=uuid4, description="Score record UUID")
    transaction_id: str = Field(..., description="Transaction identifier")
    model_version: str = Field(..., description="Model version used for scoring")
    risk_score: float = Field(..., ge=0.0, le=1.0, description="Predicted fraud probability")
    risk_label: RiskLabel = Field(..., description="Categorical risk label")
    threshold_used: float = Field(..., description="Threshold applied for flagging")
    was_flagged: bool = Field(..., description="Whether routed for human investigation")
    scoring_latency_ms: float = Field(..., description="Inference execution time in ms")
    feature_fetch_latency_ms: float = Field(..., description="Redis feature lookup time in ms")
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Scoring timestamp",
    )


class InvestigationNarrative(BaseModel):
    """
    Structured narrative generated by Groq LLM citing verifiable context evidence.
    """

    transaction_summary: str = Field(..., description="Summary of flagged transaction")
    risk_indicators: list[dict[str, str]] = Field(
        ...,
        description="List of risk factors with severity tag ([STRONG/MODERATE/WEAK]) and evidence citation",
    )
    customer_context: str = Field(
        ..., description="Historical spending baseline and pattern analysis"
    )
    recommended_action: str = Field(
        ..., description="Action recommendation: APPROVE / HOLD_FOR_REVIEW / ESCALATE_URGENT"
    )
    evidence_grounding_score: float = Field(
        default=1.0, ge=0.0, le=1.0, description="Verification grounding fidelity score"
    )
    raw_markdown: Optional[str] = Field(default=None, description="Raw LLM generated text")


class FraudCase(BaseModel):
    """
    Complete case bundle stored in PostgreSQL for analyst review.
    """

    id: UUID = Field(default_factory=uuid4, description="Case UUID")
    transaction_id: str = Field(..., description="Flagged transaction identifier")
    risk_score: float = Field(..., ge=0.0, le=1.0, description="Model risk score")
    case_context: dict[str, Any] = Field(
        default_factory=dict, description="Assembled customer, device, and merchant context"
    )
    investigation_narrative: Optional[str] = Field(
        default=None, description="LLM generated analysis"
    )
    narrative_model_version: Optional[str] = Field(
        default=None, description="LLM model/adapter version"
    )
    analyst_decision: Optional[AnalystDecision] = Field(
        default=None, description="Analyst verdict"
    )
    analyst_notes: Optional[str] = Field(default=None, description="Analyst comments")
    analyst_id: Optional[str] = Field(default=None, description="Reviewing analyst identifier")
    decision_timestamp: Optional[datetime] = Field(
        default=None, description="Time of analyst decision"
    )
    status: CaseStatus = Field(default=CaseStatus.PENDING, description="Investigation status")
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Case creation timestamp",
    )


class AnalystFeedback(BaseModel):
    """
    Input schema when an analyst submits a review decision via API.
    """

    analyst_id: str = Field(..., description="ID of reviewing analyst")
    decision: AnalystDecision = Field(..., description="Decision verdict")
    notes: Optional[str] = Field(default=None, description="Investigation notes")
